### ISSUE TITLE
Fails when compiling on iOS

### ISSUE THREAD

**Issue by Jerakin** [defold/extension-camera#7]

**Comment by britzl** [comment]
It works for me? What happens? Do you get an error?

**Comment by britzl** [comment]
Ah, no, I had a local change. Please try again.

**Comment by Jerakin** [comment]
I think it's known but probably worth mentioning. I get `SEVERE: Unsupported platform: osx` when trying to use it on osx.

**Comment by JCash** [comment]
Yes, we're in the process of fixing it.
The beta-server actually supports it (release on monday), but the Editor doesn't currently.
As a workaround, you can use bob.jar to bundle the app.
